/**
 * Frontend logo overrides keyed by school id. Takes priority over the
 * WIAA-sourced team.logo_url in TeamLogo — used for tracked entities that
 * WIAA serves no (or a wrong) logo for. The Central Wisconsin Storm is a
 * co-op registered under D.C. Everest's WIAA org, so without an override
 * its games carry DCE's evergreen mark; this gives it its own crest.
 *
 * Assets live in frontend/public/logos/ and ship as static files.
 */
import LOGO_MANIFEST from "./logoManifest.json";

const BASE = import.meta.env.BASE_URL;

export const LOGO_OVERRIDES = {
  "central-wisconsin-storm": `${BASE}logos/central-wisconsin-storm.svg`,
};

/** Local override URL for a school id, or null when there isn't one. */
export function logoOverrideFor(schoolId) {
  return schoolId ? LOGO_OVERRIDES[schoolId] ?? null : null;
}

/**
 * Locally mirrored WIAA logo for a school, or null.
 *
 * The manifest is generated by scraper/scripts/mirror_logos.py and inlined
 * at build time (Vite imports JSON), so this costs no runtime request.
 * Preferring it means a dashboard makes ~0 cross-origin image requests
 * instead of ~125 to schools.wiaawi.org, which is both much faster on the
 * slow connections a lot of this audience reads on and a great deal kinder
 * to a state association's directory server on a Friday night.
 *
 * Callers must still fall back to the live WIAA URL — see TeamLogo — so a
 * school absent from the mirror behaves exactly as it did before.
 */
export function mirroredLogoFor(schoolId) {
  const file = schoolId ? LOGO_MANIFEST[schoolId] : null;
  return file ? `${BASE}logos/${file}` : null;
}
