"""
Post-process: re-run the per-game stat merges (Bound, then MaxPreps)
against the existing dataset without a full WIAA rescrape.

Why this exists: Bound serves GitHub-runner IPs a bot challenge, so every
CI scrape indexes 0 Bound games and carries the previous run's stat lines
forward. A Bound parser fix therefore never reaches the site through the
cron — the lines have to be regenerated by a local run and committed.
Mirrors main.py's stats phase: Bound replaces a matched game's lines,
MaxPreps layers its lines on top, anything whose merges came back empty
keeps what it had, future-dated finals are stripped.

Usage:
  cd scraper
  .venv/Scripts/python.exe scripts/refresh_bound.py --sport football
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "scraper"))

from rich.console import Console  # noqa: E402

from config.loader import load_manifest  # noqa: E402
from models.schema import GameStatus  # noqa: E402
from output.writer import load_prev_rankings, read_dataset, write_dataset  # noqa: E402
from transform.normalize import build_name_index_for_manifest  # noqa: E402
from transform.rankings import compute_power_rankings  # noqa: E402
from transform.stats import (  # noqa: E402
    is_forfeit_final,
    merge_bound_stats,
    merge_maxpreps_stats,
)

DATA_DIR = REPO_ROOT / "data"
BOUND_SPORT_ABBR = {
    "football": "fb",
    "boys_basketball": "boysbasketball",
    "girls_basketball": "girlsbasketball",
    "volleyball": "vb",
}


def refresh(sport: str, console: Console, manifest) -> bool:
    ds = read_dataset(sport, DATA_DIR)
    if ds is None:
        console.print(f"[yellow]{sport}: no dataset on disk — skipping[/yellow]")
        return False

    before = {g.id: list(g.stat_leaders) for g in ds.games if g.stat_leaders}
    name_to_id = build_name_index_for_manifest(manifest)

    ds = merge_bound_stats(
        ds,
        name_to_id=name_to_id,
        sport_abbr=BOUND_SPORT_ABBR[sport],
        season=ds.meta.season,
        console=console,
    )
    ds = merge_maxpreps_stats(
        ds,
        manifest=manifest,
        name_to_id=name_to_id,
        season=ds.meta.season,
        console=console,
    )

    carried = 0
    for g in ds.games:
        if g.status is GameStatus.FINAL and not g.stat_leaders and g.id in before:
            g.stat_leaders = before[g.id]
            carried += 1
    if carried:
        console.print(f"[yellow]carried stat lines forward for {carried} game(s)[/yellow]")

    horizon = datetime.now(timezone.utc) + timedelta(days=1)
    for g in ds.games:
        if g.status is GameStatus.FINAL and g.stat_leaders and g.date > horizon:
            console.print(f"[yellow]dropped stat lines from future-dated final {g.id}[/yellow]")
            g.stat_leaders = []
        elif g.stat_leaders and is_forfeit_final(g):
            console.print(f"[yellow]dropped stat lines from forfeit {g.id}[/yellow]")
            g.stat_leaders = []

    replaced = sum(1 for g in ds.games if g.id in before and g.stat_leaders != before[g.id])
    console.print(f"[dim]{sport}: {replaced} game(s) have different stat lines than before[/dim]")

    prev = load_prev_rankings(sport, DATA_DIR)
    ds = compute_power_rankings(ds, manifest=manifest, prev_rankings=prev, console=console)
    write_dataset(ds, DATA_DIR)
    console.print(f"[green]{sport}: refreshed[/green]")
    return True


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--sport",
        action="append",
        choices=sorted(BOUND_SPORT_ABBR),
        help="Limit to one sport (repeatable). Default: football.",
    )
    args = p.parse_args()

    console = Console()
    manifest = load_manifest()
    for sport in args.sport or ["football"]:
        refresh(sport, console, manifest)
    return 0


if __name__ == "__main__":
    sys.exit(main())
